---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: CentOS7
    image: quay.io/centos/centos:centos7
    # image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    # pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
driver:
  options:
    managed: False
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman